export const COMPLETED_COURSES = [
      { termId: '2', requirement: 'CS', class: 'EECS 168', description: 'Programming I', term: '2022 Spring' },
      { termId: '3', requirement: 'CS', class: 'EECS 268', description: 'Programming II', term: '2022 Fall' },
      { termId: '5', requirement: 'CS', class: 'EECS 330', description: 'Datastructures and Algorithms', term: '2023 Fall' },
      { termId: '5', requirement: 'CS', class: 'EECS 348', description: 'Software Engineering I', term: '2023 Fall' },
      { termId: '4', requirement: 'CS', class: 'EECS 388', description: 'Embedded Systems', term: '2023 Spring' },
      { termId: '6', requirement: 'CS', class: 'EECS 447', description: 'Database Systems', term: '2024 Spring' },
      { termId: '5', requirement: 'CS', class: 'EECS 468', description: 'Programming Paradigms', term: '2023 Fall' },
      { termId: '4', requirement: 'CS', class: 'EECS 510', description: 'Theory of Computing', term: '2023 Spring' },
      { termId: '6', requirement: 'CS', class: 'EECS 565', description: 'Information and Computer Security', term: '2024 Spring' },
      { termId: '6', requirement: 'CS', class: 'EECS 678', description: 'Operating Systems', term: '2024 Spring' },
      { termId: '6', requirement: 'CS', class: 'EECS 690', description: 'Algorithms for High Performance Computing', term: '2024 Spring' },
      { termId: '1', requirement: 'MATH', class: 'MATH 125', description: 'Calc I', term: '2021 Fall' },
      { termId: '2', requirement: 'MATH', class: 'MATH 126', description: 'Calc II', term: '2022 Spring' },
      { termId: '3', requirement: 'MATH', class: 'MATH 127', description: 'Calc III', term: '2022 Fall' },
      { termId: '3', requirement: 'MATH', class: 'MATH 290', description: 'Elementary Linear Algebra', term: '2022 Fall' },
      { termId: '1', requirement: 'MATH', class: 'EECS 140', description: 'Digital Logic Design', term: '2021 Fall' },
      { termId: '3', requirement: 'MATH', class: 'EECS 210', description: 'Discrete Structures', term: '2022 Fall' },
      { termId: '5', requirement: 'MATH', class: 'EECS 461', description: 'Engineering Probability and Statistics', term: '2023 Fall'},
      { termId: '2', requirement: 'MATH', class: 'PHSX 210 216', description: 'Physics I', term: '2022 Spring' },
      { termId: '1', requirement: 'CORE', class: 'COMS 130', description: 'Speaker-Audience Communication', term: '2021 Fall' },
      { termId: '1', requirement: 'CORE', class: 'ECON 142', description: 'Principles of Microeconomics', term: '2021 Fall' },
      { termId: '4', requirement: 'CORE', class: 'GEOG 102', description: 'People, Place, and Society', term: '2023 Spring' },
      { termId: '4', requirement: 'CORE', class: 'WGSS 101', description: 'Women, Gender and Sexuality Studies', term: '2023 Spring' },
]
