name: Build and Publish with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Get Package Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main

    - name: Build and Test Angular App
      run: |
        npm ci
        npm run test
        npm run build --prod
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: morriswa
        password: ${{ secrets.DOCKER_KEY }}

    - name: Build and Publish Container
      run: |
        docker build . -t morriswa/portfolio:${{ steps.package-version.outputs.current-version}}
        docker push morriswa/portfolio:${{ steps.package-version.outputs.current-version}}
