name: Build and Publish with Docker 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Package Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
  
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: morriswa
        password: ${{ secrets.DOCKER_KEY }}

    - name: Build and Publish Container 
      run: |
        docker build . -t morriswa/portfolio:${{ steps.package-version.outputs.current-version}}
        docker push morriswa/portfolio:${{ steps.package-version.outputs.current-version}}
